# Generated by Django 5.1.4 on 2025-01-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='../catalogue/static/catalogue/images/default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
