# Generated by Django 5.1.4 on 2025-01-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0002_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='static/catalogue/img/default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
