# Generated by Django 5.1.4 on 2025-01-28 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogue', '0003_alter_article_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='photo',
            field=models.ImageField(default='catalogue/img/default.jpg', upload_to='photos/%Y/%m/%d/'),
        ),
    ]
